general:
  name: "pretrain_nb101"
  seed: 42

dataset:
  name: "nasbench101"
  data_dir: "data/NASBench101/raw"
  filter_threshold: null
  split_seed: 0
  limit: "all"

model:
  n_layers: 8
  diffusion_steps: 800
  noise_schedule: "cosine"
  hidden_dims: {dx: 256, de: 64, dy: 64, n_head: 8, dim_ffX: 256, dim_ffE: 128, dim_ffy: 128}
  hidden_mlp_dims: {X: 256, E: 128, y: 128}
  lambda_train: [5.0, 0.0]

train:
  epochs: 800
  batch_size: 512
  lr: 0.0002
  weight_decay: 1.0e-12
  check_val_every_n_epochs: 20
